# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/karthikgopalan/Documents/cs184-final

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/karthikgopalan/Documents/cs184-final

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/opt/local/bin/cpack --config ./CPackSourceConfig.cmake /Users/karthikgopalan/Documents/cs184-final/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.15.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"devel\" \"examples\" \"lib\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/opt/local/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/karthikgopalan/Documents/cs184-final/CMakeFiles /Users/karthikgopalan/Documents/cs184-final/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/karthikgopalan/Documents/cs184-final/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f ext/embree/CMakeFiles/uninstall.dir/build.make ext/embree/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named sys

# Build rule for target.
sys: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sys
.PHONY : sys

# fast build rule for target.
sys/fast:
	$(MAKE) -f ext/embree/common/sys/CMakeFiles/sys.dir/build.make ext/embree/common/sys/CMakeFiles/sys.dir/build
.PHONY : sys/fast

#=============================================================================
# Target rules for targets named math

# Build rule for target.
math: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 math
.PHONY : math

# fast build rule for target.
math/fast:
	$(MAKE) -f ext/embree/common/math/CMakeFiles/math.dir/build.make ext/embree/common/math/CMakeFiles/math.dir/build
.PHONY : math/fast

#=============================================================================
# Target rules for targets named simd

# Build rule for target.
simd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simd
.PHONY : simd

# fast build rule for target.
simd/fast:
	$(MAKE) -f ext/embree/common/simd/CMakeFiles/simd.dir/build.make ext/embree/common/simd/CMakeFiles/simd.dir/build
.PHONY : simd/fast

#=============================================================================
# Target rules for targets named lexers

# Build rule for target.
lexers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lexers
.PHONY : lexers

# fast build rule for target.
lexers/fast:
	$(MAKE) -f ext/embree/common/lexers/CMakeFiles/lexers.dir/build.make ext/embree/common/lexers/CMakeFiles/lexers.dir/build
.PHONY : lexers/fast

#=============================================================================
# Target rules for targets named tasking

# Build rule for target.
tasking: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tasking
.PHONY : tasking

# fast build rule for target.
tasking/fast:
	$(MAKE) -f ext/embree/common/tasking/CMakeFiles/tasking.dir/build.make ext/embree/common/tasking/CMakeFiles/tasking.dir/build
.PHONY : tasking/fast

#=============================================================================
# Target rules for targets named algorithms

# Build rule for target.
algorithms: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 algorithms
.PHONY : algorithms

# fast build rule for target.
algorithms/fast:
	$(MAKE) -f ext/embree/common/algorithms/CMakeFiles/algorithms.dir/build.make ext/embree/common/algorithms/CMakeFiles/algorithms.dir/build
.PHONY : algorithms/fast

#=============================================================================
# Target rules for targets named embree_avx

# Build rule for target.
embree_avx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 embree_avx
.PHONY : embree_avx

# fast build rule for target.
embree_avx/fast:
	$(MAKE) -f ext/embree/kernels/CMakeFiles/embree_avx.dir/build.make ext/embree/kernels/CMakeFiles/embree_avx.dir/build
.PHONY : embree_avx/fast

#=============================================================================
# Target rules for targets named embree_sse42

# Build rule for target.
embree_sse42: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 embree_sse42
.PHONY : embree_sse42

# fast build rule for target.
embree_sse42/fast:
	$(MAKE) -f ext/embree/kernels/CMakeFiles/embree_sse42.dir/build.make ext/embree/kernels/CMakeFiles/embree_sse42.dir/build
.PHONY : embree_sse42/fast

#=============================================================================
# Target rules for targets named embree_avx2

# Build rule for target.
embree_avx2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 embree_avx2
.PHONY : embree_avx2

# fast build rule for target.
embree_avx2/fast:
	$(MAKE) -f ext/embree/kernels/CMakeFiles/embree_avx2.dir/build.make ext/embree/kernels/CMakeFiles/embree_avx2.dir/build
.PHONY : embree_avx2/fast

#=============================================================================
# Target rules for targets named embree

# Build rule for target.
embree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 embree
.PHONY : embree

# fast build rule for target.
embree/fast:
	$(MAKE) -f ext/embree/kernels/CMakeFiles/embree.dir/build.make ext/embree/kernels/CMakeFiles/embree.dir/build
.PHONY : embree/fast

#=============================================================================
# Target rules for targets named image

# Build rule for target.
image: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 image
.PHONY : image

# fast build rule for target.
image/fast:
	$(MAKE) -f ext/embree/tutorials/common/image/CMakeFiles/image.dir/build.make ext/embree/tutorials/common/image/CMakeFiles/image.dir/build
.PHONY : image/fast

#=============================================================================
# Target rules for targets named noise_ispc

# Build rule for target.
noise_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 noise_ispc
.PHONY : noise_ispc

# fast build rule for target.
noise_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/common/tutorial/CMakeFiles/noise_ispc.dir/build.make ext/embree/tutorials/common/tutorial/CMakeFiles/noise_ispc.dir/build
.PHONY : noise_ispc/fast

#=============================================================================
# Target rules for targets named tutorial_ispc

# Build rule for target.
tutorial_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tutorial_ispc
.PHONY : tutorial_ispc

# fast build rule for target.
tutorial_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/common/tutorial/CMakeFiles/tutorial_ispc.dir/build.make ext/embree/tutorials/common/tutorial/CMakeFiles/tutorial_ispc.dir/build
.PHONY : tutorial_ispc/fast

#=============================================================================
# Target rules for targets named noise

# Build rule for target.
noise: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 noise
.PHONY : noise

# fast build rule for target.
noise/fast:
	$(MAKE) -f ext/embree/tutorials/common/tutorial/CMakeFiles/noise.dir/build.make ext/embree/tutorials/common/tutorial/CMakeFiles/noise.dir/build
.PHONY : noise/fast

#=============================================================================
# Target rules for targets named tutorial

# Build rule for target.
tutorial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tutorial
.PHONY : tutorial

# fast build rule for target.
tutorial/fast:
	$(MAKE) -f ext/embree/tutorials/common/tutorial/CMakeFiles/tutorial.dir/build.make ext/embree/tutorials/common/tutorial/CMakeFiles/tutorial.dir/build
.PHONY : tutorial/fast

#=============================================================================
# Target rules for targets named scenegraph

# Build rule for target.
scenegraph: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scenegraph
.PHONY : scenegraph

# fast build rule for target.
scenegraph/fast:
	$(MAKE) -f ext/embree/tutorials/common/scenegraph/CMakeFiles/scenegraph.dir/build.make ext/embree/tutorials/common/scenegraph/CMakeFiles/scenegraph.dir/build
.PHONY : scenegraph/fast

#=============================================================================
# Target rules for targets named lights_ispc

# Build rule for target.
lights_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lights_ispc
.PHONY : lights_ispc

# fast build rule for target.
lights_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/common/lights/CMakeFiles/lights_ispc.dir/build.make ext/embree/tutorials/common/lights/CMakeFiles/lights_ispc.dir/build
.PHONY : lights_ispc/fast

#=============================================================================
# Target rules for targets named lights

# Build rule for target.
lights: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lights
.PHONY : lights

# fast build rule for target.
lights/fast:
	$(MAKE) -f ext/embree/tutorials/common/lights/CMakeFiles/lights.dir/build.make ext/embree/tutorials/common/lights/CMakeFiles/lights.dir/build
.PHONY : lights/fast

#=============================================================================
# Target rules for targets named texture_ispc

# Build rule for target.
texture_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 texture_ispc
.PHONY : texture_ispc

# fast build rule for target.
texture_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/common/texture/CMakeFiles/texture_ispc.dir/build.make ext/embree/tutorials/common/texture/CMakeFiles/texture_ispc.dir/build
.PHONY : texture_ispc/fast

#=============================================================================
# Target rules for targets named texture

# Build rule for target.
texture: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 texture
.PHONY : texture

# fast build rule for target.
texture/fast:
	$(MAKE) -f ext/embree/tutorials/common/texture/CMakeFiles/texture.dir/build.make ext/embree/tutorials/common/texture/CMakeFiles/texture.dir/build
.PHONY : texture/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) -f ext/embree/tutorials/common/imgui/CMakeFiles/imgui.dir/build.make ext/embree/tutorials/common/imgui/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named verify

# Build rule for target.
verify: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 verify
.PHONY : verify

# fast build rule for target.
verify/fast:
	$(MAKE) -f ext/embree/tutorials/verify/CMakeFiles/verify.dir/build.make ext/embree/tutorials/verify/CMakeFiles/verify.dir/build
.PHONY : verify/fast

#=============================================================================
# Target rules for targets named c99_compile_test

# Build rule for target.
c99_compile_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 c99_compile_test
.PHONY : c99_compile_test

# fast build rule for target.
c99_compile_test/fast:
	$(MAKE) -f ext/embree/tutorials/verify/CMakeFiles/c99_compile_test.dir/build.make ext/embree/tutorials/verify/CMakeFiles/c99_compile_test.dir/build
.PHONY : c99_compile_test/fast

#=============================================================================
# Target rules for targets named triangle_geometry_ispc

# Build rule for target.
triangle_geometry_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangle_geometry_ispc
.PHONY : triangle_geometry_ispc

# fast build rule for target.
triangle_geometry_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/triangle_geometry/CMakeFiles/triangle_geometry_ispc.dir/build.make ext/embree/tutorials/triangle_geometry/CMakeFiles/triangle_geometry_ispc.dir/build
.PHONY : triangle_geometry_ispc/fast

#=============================================================================
# Target rules for targets named triangle_geometry

# Build rule for target.
triangle_geometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangle_geometry
.PHONY : triangle_geometry

# fast build rule for target.
triangle_geometry/fast:
	$(MAKE) -f ext/embree/tutorials/triangle_geometry/CMakeFiles/triangle_geometry.dir/build.make ext/embree/tutorials/triangle_geometry/CMakeFiles/triangle_geometry.dir/build
.PHONY : triangle_geometry/fast

#=============================================================================
# Target rules for targets named dynamic_scene_ispc

# Build rule for target.
dynamic_scene_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dynamic_scene_ispc
.PHONY : dynamic_scene_ispc

# fast build rule for target.
dynamic_scene_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/dynamic_scene/CMakeFiles/dynamic_scene_ispc.dir/build.make ext/embree/tutorials/dynamic_scene/CMakeFiles/dynamic_scene_ispc.dir/build
.PHONY : dynamic_scene_ispc/fast

#=============================================================================
# Target rules for targets named dynamic_scene

# Build rule for target.
dynamic_scene: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dynamic_scene
.PHONY : dynamic_scene

# fast build rule for target.
dynamic_scene/fast:
	$(MAKE) -f ext/embree/tutorials/dynamic_scene/CMakeFiles/dynamic_scene.dir/build.make ext/embree/tutorials/dynamic_scene/CMakeFiles/dynamic_scene.dir/build
.PHONY : dynamic_scene/fast

#=============================================================================
# Target rules for targets named user_geometry_ispc

# Build rule for target.
user_geometry_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 user_geometry_ispc
.PHONY : user_geometry_ispc

# fast build rule for target.
user_geometry_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/user_geometry/CMakeFiles/user_geometry_ispc.dir/build.make ext/embree/tutorials/user_geometry/CMakeFiles/user_geometry_ispc.dir/build
.PHONY : user_geometry_ispc/fast

#=============================================================================
# Target rules for targets named user_geometry

# Build rule for target.
user_geometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 user_geometry
.PHONY : user_geometry

# fast build rule for target.
user_geometry/fast:
	$(MAKE) -f ext/embree/tutorials/user_geometry/CMakeFiles/user_geometry.dir/build.make ext/embree/tutorials/user_geometry/CMakeFiles/user_geometry.dir/build
.PHONY : user_geometry/fast

#=============================================================================
# Target rules for targets named viewer_ispc

# Build rule for target.
viewer_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 viewer_ispc
.PHONY : viewer_ispc

# fast build rule for target.
viewer_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/viewer/CMakeFiles/viewer_ispc.dir/build.make ext/embree/tutorials/viewer/CMakeFiles/viewer_ispc.dir/build
.PHONY : viewer_ispc/fast

#=============================================================================
# Target rules for targets named viewer

# Build rule for target.
viewer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 viewer
.PHONY : viewer

# fast build rule for target.
viewer/fast:
	$(MAKE) -f ext/embree/tutorials/viewer/CMakeFiles/viewer.dir/build.make ext/embree/tutorials/viewer/CMakeFiles/viewer.dir/build
.PHONY : viewer/fast

#=============================================================================
# Target rules for targets named instanced_geometry

# Build rule for target.
instanced_geometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 instanced_geometry
.PHONY : instanced_geometry

# fast build rule for target.
instanced_geometry/fast:
	$(MAKE) -f ext/embree/tutorials/instanced_geometry/CMakeFiles/instanced_geometry.dir/build.make ext/embree/tutorials/instanced_geometry/CMakeFiles/instanced_geometry.dir/build
.PHONY : instanced_geometry/fast

#=============================================================================
# Target rules for targets named instanced_geometry_ispc

# Build rule for target.
instanced_geometry_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 instanced_geometry_ispc
.PHONY : instanced_geometry_ispc

# fast build rule for target.
instanced_geometry_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/instanced_geometry/CMakeFiles/instanced_geometry_ispc.dir/build.make ext/embree/tutorials/instanced_geometry/CMakeFiles/instanced_geometry_ispc.dir/build
.PHONY : instanced_geometry_ispc/fast

#=============================================================================
# Target rules for targets named intersection_filter_ispc

# Build rule for target.
intersection_filter_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 intersection_filter_ispc
.PHONY : intersection_filter_ispc

# fast build rule for target.
intersection_filter_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/intersection_filter/CMakeFiles/intersection_filter_ispc.dir/build.make ext/embree/tutorials/intersection_filter/CMakeFiles/intersection_filter_ispc.dir/build
.PHONY : intersection_filter_ispc/fast

#=============================================================================
# Target rules for targets named intersection_filter

# Build rule for target.
intersection_filter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 intersection_filter
.PHONY : intersection_filter

# fast build rule for target.
intersection_filter/fast:
	$(MAKE) -f ext/embree/tutorials/intersection_filter/CMakeFiles/intersection_filter.dir/build.make ext/embree/tutorials/intersection_filter/CMakeFiles/intersection_filter.dir/build
.PHONY : intersection_filter/fast

#=============================================================================
# Target rules for targets named pathtracer

# Build rule for target.
pathtracer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pathtracer
.PHONY : pathtracer

# fast build rule for target.
pathtracer/fast:
	$(MAKE) -f ext/embree/tutorials/pathtracer/CMakeFiles/pathtracer.dir/build.make ext/embree/tutorials/pathtracer/CMakeFiles/pathtracer.dir/build
.PHONY : pathtracer/fast

#=============================================================================
# Target rules for targets named pathtracer_ispc

# Build rule for target.
pathtracer_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pathtracer_ispc
.PHONY : pathtracer_ispc

# fast build rule for target.
pathtracer_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/pathtracer/CMakeFiles/pathtracer_ispc.dir/build.make ext/embree/tutorials/pathtracer/CMakeFiles/pathtracer_ispc.dir/build
.PHONY : pathtracer_ispc/fast

#=============================================================================
# Target rules for targets named hair_geometry_ispc

# Build rule for target.
hair_geometry_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hair_geometry_ispc
.PHONY : hair_geometry_ispc

# fast build rule for target.
hair_geometry_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/hair_geometry/CMakeFiles/hair_geometry_ispc.dir/build.make ext/embree/tutorials/hair_geometry/CMakeFiles/hair_geometry_ispc.dir/build
.PHONY : hair_geometry_ispc/fast

#=============================================================================
# Target rules for targets named hair_geometry

# Build rule for target.
hair_geometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hair_geometry
.PHONY : hair_geometry

# fast build rule for target.
hair_geometry/fast:
	$(MAKE) -f ext/embree/tutorials/hair_geometry/CMakeFiles/hair_geometry.dir/build.make ext/embree/tutorials/hair_geometry/CMakeFiles/hair_geometry.dir/build
.PHONY : hair_geometry/fast

#=============================================================================
# Target rules for targets named subdivision_geometry_ispc

# Build rule for target.
subdivision_geometry_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 subdivision_geometry_ispc
.PHONY : subdivision_geometry_ispc

# fast build rule for target.
subdivision_geometry_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/subdivision_geometry/CMakeFiles/subdivision_geometry_ispc.dir/build.make ext/embree/tutorials/subdivision_geometry/CMakeFiles/subdivision_geometry_ispc.dir/build
.PHONY : subdivision_geometry_ispc/fast

#=============================================================================
# Target rules for targets named subdivision_geometry

# Build rule for target.
subdivision_geometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 subdivision_geometry
.PHONY : subdivision_geometry

# fast build rule for target.
subdivision_geometry/fast:
	$(MAKE) -f ext/embree/tutorials/subdivision_geometry/CMakeFiles/subdivision_geometry.dir/build.make ext/embree/tutorials/subdivision_geometry/CMakeFiles/subdivision_geometry.dir/build
.PHONY : subdivision_geometry/fast

#=============================================================================
# Target rules for targets named displacement_geometry_ispc

# Build rule for target.
displacement_geometry_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 displacement_geometry_ispc
.PHONY : displacement_geometry_ispc

# fast build rule for target.
displacement_geometry_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/displacement_geometry/CMakeFiles/displacement_geometry_ispc.dir/build.make ext/embree/tutorials/displacement_geometry/CMakeFiles/displacement_geometry_ispc.dir/build
.PHONY : displacement_geometry_ispc/fast

#=============================================================================
# Target rules for targets named displacement_geometry

# Build rule for target.
displacement_geometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 displacement_geometry
.PHONY : displacement_geometry

# fast build rule for target.
displacement_geometry/fast:
	$(MAKE) -f ext/embree/tutorials/displacement_geometry/CMakeFiles/displacement_geometry.dir/build.make ext/embree/tutorials/displacement_geometry/CMakeFiles/displacement_geometry.dir/build
.PHONY : displacement_geometry/fast

#=============================================================================
# Target rules for targets named grid_geometry

# Build rule for target.
grid_geometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grid_geometry
.PHONY : grid_geometry

# fast build rule for target.
grid_geometry/fast:
	$(MAKE) -f ext/embree/tutorials/grid_geometry/CMakeFiles/grid_geometry.dir/build.make ext/embree/tutorials/grid_geometry/CMakeFiles/grid_geometry.dir/build
.PHONY : grid_geometry/fast

#=============================================================================
# Target rules for targets named grid_geometry_ispc

# Build rule for target.
grid_geometry_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grid_geometry_ispc
.PHONY : grid_geometry_ispc

# fast build rule for target.
grid_geometry_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/grid_geometry/CMakeFiles/grid_geometry_ispc.dir/build.make ext/embree/tutorials/grid_geometry/CMakeFiles/grid_geometry_ispc.dir/build
.PHONY : grid_geometry_ispc/fast

#=============================================================================
# Target rules for targets named bvh_builder

# Build rule for target.
bvh_builder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bvh_builder
.PHONY : bvh_builder

# fast build rule for target.
bvh_builder/fast:
	$(MAKE) -f ext/embree/tutorials/bvh_builder/CMakeFiles/bvh_builder.dir/build.make ext/embree/tutorials/bvh_builder/CMakeFiles/bvh_builder.dir/build
.PHONY : bvh_builder/fast

#=============================================================================
# Target rules for targets named lazy_geometry_ispc

# Build rule for target.
lazy_geometry_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lazy_geometry_ispc
.PHONY : lazy_geometry_ispc

# fast build rule for target.
lazy_geometry_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/lazy_geometry/CMakeFiles/lazy_geometry_ispc.dir/build.make ext/embree/tutorials/lazy_geometry/CMakeFiles/lazy_geometry_ispc.dir/build
.PHONY : lazy_geometry_ispc/fast

#=============================================================================
# Target rules for targets named lazy_geometry

# Build rule for target.
lazy_geometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lazy_geometry
.PHONY : lazy_geometry

# fast build rule for target.
lazy_geometry/fast:
	$(MAKE) -f ext/embree/tutorials/lazy_geometry/CMakeFiles/lazy_geometry.dir/build.make ext/embree/tutorials/lazy_geometry/CMakeFiles/lazy_geometry.dir/build
.PHONY : lazy_geometry/fast

#=============================================================================
# Target rules for targets named bvh_access

# Build rule for target.
bvh_access: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bvh_access
.PHONY : bvh_access

# fast build rule for target.
bvh_access/fast:
	$(MAKE) -f ext/embree/tutorials/bvh_access/CMakeFiles/bvh_access.dir/build.make ext/embree/tutorials/bvh_access/CMakeFiles/bvh_access.dir/build
.PHONY : bvh_access/fast

#=============================================================================
# Target rules for targets named minimal

# Build rule for target.
minimal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 minimal
.PHONY : minimal

# fast build rule for target.
minimal/fast:
	$(MAKE) -f ext/embree/tutorials/minimal/CMakeFiles/minimal.dir/build.make ext/embree/tutorials/minimal/CMakeFiles/minimal.dir/build
.PHONY : minimal/fast

#=============================================================================
# Target rules for targets named motion_blur_geometry_ispc

# Build rule for target.
motion_blur_geometry_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 motion_blur_geometry_ispc
.PHONY : motion_blur_geometry_ispc

# fast build rule for target.
motion_blur_geometry_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/motion_blur_geometry/CMakeFiles/motion_blur_geometry_ispc.dir/build.make ext/embree/tutorials/motion_blur_geometry/CMakeFiles/motion_blur_geometry_ispc.dir/build
.PHONY : motion_blur_geometry_ispc/fast

#=============================================================================
# Target rules for targets named motion_blur_geometry

# Build rule for target.
motion_blur_geometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 motion_blur_geometry
.PHONY : motion_blur_geometry

# fast build rule for target.
motion_blur_geometry/fast:
	$(MAKE) -f ext/embree/tutorials/motion_blur_geometry/CMakeFiles/motion_blur_geometry.dir/build.make ext/embree/tutorials/motion_blur_geometry/CMakeFiles/motion_blur_geometry.dir/build
.PHONY : motion_blur_geometry/fast

#=============================================================================
# Target rules for targets named interpolation

# Build rule for target.
interpolation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 interpolation
.PHONY : interpolation

# fast build rule for target.
interpolation/fast:
	$(MAKE) -f ext/embree/tutorials/interpolation/CMakeFiles/interpolation.dir/build.make ext/embree/tutorials/interpolation/CMakeFiles/interpolation.dir/build
.PHONY : interpolation/fast

#=============================================================================
# Target rules for targets named interpolation_ispc

# Build rule for target.
interpolation_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 interpolation_ispc
.PHONY : interpolation_ispc

# fast build rule for target.
interpolation_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/interpolation/CMakeFiles/interpolation_ispc.dir/build.make ext/embree/tutorials/interpolation/CMakeFiles/interpolation_ispc.dir/build
.PHONY : interpolation_ispc/fast

#=============================================================================
# Target rules for targets named convert

# Build rule for target.
convert: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 convert
.PHONY : convert

# fast build rule for target.
convert/fast:
	$(MAKE) -f ext/embree/tutorials/convert/CMakeFiles/convert.dir/build.make ext/embree/tutorials/convert/CMakeFiles/convert.dir/build
.PHONY : convert/fast

#=============================================================================
# Target rules for targets named curve_geometry_ispc

# Build rule for target.
curve_geometry_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 curve_geometry_ispc
.PHONY : curve_geometry_ispc

# fast build rule for target.
curve_geometry_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/curve_geometry/CMakeFiles/curve_geometry_ispc.dir/build.make ext/embree/tutorials/curve_geometry/CMakeFiles/curve_geometry_ispc.dir/build
.PHONY : curve_geometry_ispc/fast

#=============================================================================
# Target rules for targets named curve_geometry

# Build rule for target.
curve_geometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 curve_geometry
.PHONY : curve_geometry

# fast build rule for target.
curve_geometry/fast:
	$(MAKE) -f ext/embree/tutorials/curve_geometry/CMakeFiles/curve_geometry.dir/build.make ext/embree/tutorials/curve_geometry/CMakeFiles/curve_geometry.dir/build
.PHONY : curve_geometry/fast

#=============================================================================
# Target rules for targets named point_geometry_ispc

# Build rule for target.
point_geometry_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 point_geometry_ispc
.PHONY : point_geometry_ispc

# fast build rule for target.
point_geometry_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/point_geometry/CMakeFiles/point_geometry_ispc.dir/build.make ext/embree/tutorials/point_geometry/CMakeFiles/point_geometry_ispc.dir/build
.PHONY : point_geometry_ispc/fast

#=============================================================================
# Target rules for targets named point_geometry

# Build rule for target.
point_geometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 point_geometry
.PHONY : point_geometry

# fast build rule for target.
point_geometry/fast:
	$(MAKE) -f ext/embree/tutorials/point_geometry/CMakeFiles/point_geometry.dir/build.make ext/embree/tutorials/point_geometry/CMakeFiles/point_geometry.dir/build
.PHONY : point_geometry/fast

#=============================================================================
# Target rules for targets named buildbench

# Build rule for target.
buildbench: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 buildbench
.PHONY : buildbench

# fast build rule for target.
buildbench/fast:
	$(MAKE) -f ext/embree/tutorials/buildbench/CMakeFiles/buildbench.dir/build.make ext/embree/tutorials/buildbench/CMakeFiles/buildbench.dir/build
.PHONY : buildbench/fast

#=============================================================================
# Target rules for targets named collide

# Build rule for target.
collide: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 collide
.PHONY : collide

# fast build rule for target.
collide/fast:
	$(MAKE) -f ext/embree/tutorials/collide/CMakeFiles/collide.dir/build.make ext/embree/tutorials/collide/CMakeFiles/collide.dir/build
.PHONY : collide/fast

#=============================================================================
# Target rules for targets named closest_point_ispc

# Build rule for target.
closest_point_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 closest_point_ispc
.PHONY : closest_point_ispc

# fast build rule for target.
closest_point_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/closest_point/CMakeFiles/closest_point_ispc.dir/build.make ext/embree/tutorials/closest_point/CMakeFiles/closest_point_ispc.dir/build
.PHONY : closest_point_ispc/fast

#=============================================================================
# Target rules for targets named closest_point

# Build rule for target.
closest_point: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 closest_point
.PHONY : closest_point

# fast build rule for target.
closest_point/fast:
	$(MAKE) -f ext/embree/tutorials/closest_point/CMakeFiles/closest_point.dir/build.make ext/embree/tutorials/closest_point/CMakeFiles/closest_point.dir/build
.PHONY : closest_point/fast

#=============================================================================
# Target rules for targets named voronoi_ispc

# Build rule for target.
voronoi_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 voronoi_ispc
.PHONY : voronoi_ispc

# fast build rule for target.
voronoi_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/voronoi/CMakeFiles/voronoi_ispc.dir/build.make ext/embree/tutorials/voronoi/CMakeFiles/voronoi_ispc.dir/build
.PHONY : voronoi_ispc/fast

#=============================================================================
# Target rules for targets named voronoi

# Build rule for target.
voronoi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 voronoi
.PHONY : voronoi

# fast build rule for target.
voronoi/fast:
	$(MAKE) -f ext/embree/tutorials/voronoi/CMakeFiles/voronoi.dir/build.make ext/embree/tutorials/voronoi/CMakeFiles/voronoi.dir/build
.PHONY : voronoi/fast

#=============================================================================
# Target rules for targets named next_hit

# Build rule for target.
next_hit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 next_hit
.PHONY : next_hit

# fast build rule for target.
next_hit/fast:
	$(MAKE) -f ext/embree/tutorials/next_hit/CMakeFiles/next_hit.dir/build.make ext/embree/tutorials/next_hit/CMakeFiles/next_hit.dir/build
.PHONY : next_hit/fast

#=============================================================================
# Target rules for targets named multiscene_geometry

# Build rule for target.
multiscene_geometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multiscene_geometry
.PHONY : multiscene_geometry

# fast build rule for target.
multiscene_geometry/fast:
	$(MAKE) -f ext/embree/tutorials/multiscene_geometry/CMakeFiles/multiscene_geometry.dir/build.make ext/embree/tutorials/multiscene_geometry/CMakeFiles/multiscene_geometry.dir/build
.PHONY : multiscene_geometry/fast

#=============================================================================
# Target rules for targets named quaternion_motion_blur

# Build rule for target.
quaternion_motion_blur: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 quaternion_motion_blur
.PHONY : quaternion_motion_blur

# fast build rule for target.
quaternion_motion_blur/fast:
	$(MAKE) -f ext/embree/tutorials/quaternion_motion_blur/CMakeFiles/quaternion_motion_blur.dir/build.make ext/embree/tutorials/quaternion_motion_blur/CMakeFiles/quaternion_motion_blur.dir/build
.PHONY : quaternion_motion_blur/fast

#=============================================================================
# Target rules for targets named quaternion_motion_blur_ispc

# Build rule for target.
quaternion_motion_blur_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 quaternion_motion_blur_ispc
.PHONY : quaternion_motion_blur_ispc

# fast build rule for target.
quaternion_motion_blur_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/quaternion_motion_blur/CMakeFiles/quaternion_motion_blur_ispc.dir/build.make ext/embree/tutorials/quaternion_motion_blur/CMakeFiles/quaternion_motion_blur_ispc.dir/build
.PHONY : quaternion_motion_blur_ispc/fast

#=============================================================================
# Target rules for targets named viewer_stream_ispc

# Build rule for target.
viewer_stream_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 viewer_stream_ispc
.PHONY : viewer_stream_ispc

# fast build rule for target.
viewer_stream_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/viewer_stream/CMakeFiles/viewer_stream_ispc.dir/build.make ext/embree/tutorials/viewer_stream/CMakeFiles/viewer_stream_ispc.dir/build
.PHONY : viewer_stream_ispc/fast

#=============================================================================
# Target rules for targets named viewer_stream

# Build rule for target.
viewer_stream: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 viewer_stream
.PHONY : viewer_stream

# fast build rule for target.
viewer_stream/fast:
	$(MAKE) -f ext/embree/tutorials/viewer_stream/CMakeFiles/viewer_stream.dir/build.make ext/embree/tutorials/viewer_stream/CMakeFiles/viewer_stream.dir/build
.PHONY : viewer_stream/fast

#=============================================================================
# Target rules for targets named viewer_anim_ispc

# Build rule for target.
viewer_anim_ispc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 viewer_anim_ispc
.PHONY : viewer_anim_ispc

# fast build rule for target.
viewer_anim_ispc/fast:
	$(MAKE) -f ext/embree/tutorials/viewer_anim/CMakeFiles/viewer_anim_ispc.dir/build.make ext/embree/tutorials/viewer_anim/CMakeFiles/viewer_anim_ispc.dir/build
.PHONY : viewer_anim_ispc/fast

#=============================================================================
# Target rules for targets named viewer_anim

# Build rule for target.
viewer_anim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 viewer_anim
.PHONY : viewer_anim

# fast build rule for target.
viewer_anim/fast:
	$(MAKE) -f ext/embree/tutorials/viewer_anim/CMakeFiles/viewer_anim.dir/build.make ext/embree/tutorials/viewer_anim/CMakeFiles/viewer_anim.dir/build
.PHONY : viewer_anim/fast

#=============================================================================
# Target rules for targets named nanogui

# Build rule for target.
nanogui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nanogui
.PHONY : nanogui

# fast build rule for target.
nanogui/fast:
	$(MAKE) -f ext/nanogui/CMakeFiles/nanogui.dir/build.make ext/nanogui/CMakeFiles/nanogui.dir/build
.PHONY : nanogui/fast

#=============================================================================
# Target rules for targets named nanogui-obj

# Build rule for target.
nanogui-obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nanogui-obj
.PHONY : nanogui-obj

# fast build rule for target.
nanogui-obj/fast:
	$(MAKE) -f ext/nanogui/CMakeFiles/nanogui-obj.dir/build.make ext/nanogui/CMakeFiles/nanogui-obj.dir/build
.PHONY : nanogui-obj/fast

#=============================================================================
# Target rules for targets named glfw_objects

# Build rule for target.
glfw_objects: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw_objects
.PHONY : glfw_objects

# fast build rule for target.
glfw_objects/fast:
	$(MAKE) -f ext/nanogui/ext_build/glfw/src/CMakeFiles/glfw_objects.dir/build.make ext/nanogui/ext_build/glfw/src/CMakeFiles/glfw_objects.dir/build
.PHONY : glfw_objects/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f ext/nanogui/ext_build/glfw/src/CMakeFiles/glfw.dir/build.make ext/nanogui/ext_build/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named CGL

# Build rule for target.
CGL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGL
.PHONY : CGL

# fast build rule for target.
CGL/fast:
	$(MAKE) -f CGL/src/CMakeFiles/CGL.dir/build.make CGL/src/CMakeFiles/CGL.dir/build
.PHONY : CGL/fast

#=============================================================================
# Target rules for targets named clothsim

# Build rule for target.
clothsim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clothsim
.PHONY : clothsim

# fast build rule for target.
clothsim/fast:
	$(MAKE) -f src/CMakeFiles/clothsim.dir/build.make src/CMakeFiles/clothsim.dir/build
.PHONY : clothsim/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... install"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... uninstall"
	@echo "... sys"
	@echo "... math"
	@echo "... simd"
	@echo "... lexers"
	@echo "... tasking"
	@echo "... algorithms"
	@echo "... embree_avx"
	@echo "... embree_sse42"
	@echo "... embree_avx2"
	@echo "... embree"
	@echo "... image"
	@echo "... noise_ispc"
	@echo "... tutorial_ispc"
	@echo "... noise"
	@echo "... tutorial"
	@echo "... scenegraph"
	@echo "... lights_ispc"
	@echo "... lights"
	@echo "... texture_ispc"
	@echo "... texture"
	@echo "... imgui"
	@echo "... verify"
	@echo "... c99_compile_test"
	@echo "... triangle_geometry_ispc"
	@echo "... triangle_geometry"
	@echo "... dynamic_scene_ispc"
	@echo "... dynamic_scene"
	@echo "... user_geometry_ispc"
	@echo "... user_geometry"
	@echo "... viewer_ispc"
	@echo "... viewer"
	@echo "... instanced_geometry"
	@echo "... instanced_geometry_ispc"
	@echo "... intersection_filter_ispc"
	@echo "... intersection_filter"
	@echo "... pathtracer"
	@echo "... pathtracer_ispc"
	@echo "... hair_geometry_ispc"
	@echo "... hair_geometry"
	@echo "... subdivision_geometry_ispc"
	@echo "... subdivision_geometry"
	@echo "... displacement_geometry_ispc"
	@echo "... displacement_geometry"
	@echo "... grid_geometry"
	@echo "... grid_geometry_ispc"
	@echo "... bvh_builder"
	@echo "... lazy_geometry_ispc"
	@echo "... lazy_geometry"
	@echo "... bvh_access"
	@echo "... minimal"
	@echo "... motion_blur_geometry_ispc"
	@echo "... motion_blur_geometry"
	@echo "... interpolation"
	@echo "... interpolation_ispc"
	@echo "... convert"
	@echo "... curve_geometry_ispc"
	@echo "... curve_geometry"
	@echo "... point_geometry_ispc"
	@echo "... point_geometry"
	@echo "... buildbench"
	@echo "... collide"
	@echo "... closest_point_ispc"
	@echo "... closest_point"
	@echo "... voronoi_ispc"
	@echo "... voronoi"
	@echo "... next_hit"
	@echo "... multiscene_geometry"
	@echo "... quaternion_motion_blur"
	@echo "... quaternion_motion_blur_ispc"
	@echo "... viewer_stream_ispc"
	@echo "... viewer_stream"
	@echo "... viewer_anim_ispc"
	@echo "... viewer_anim"
	@echo "... nanogui"
	@echo "... nanogui-obj"
	@echo "... glfw_objects"
	@echo "... glfw"
	@echo "... CGL"
	@echo "... clothsim"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

